name: Load Testing with k6

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # allows manual trigger

jobs:
  load-test:
    name: Run k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg ca-certificates
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 770F1DBB3C0A1F6E
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6
      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 load test
        run: |
          k6 run rekartVerificationApi-test.js
