name: Load Testing with k6

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # allows manual trigger

jobs:
  load-test:
    name: Run k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup k6
      #   uses: grafana/setup-k6-action@v1

      - name: Run k6 load test
        run: |
          k6 run rekartVerificationApi-test.js
